### ISSUE TITLE
Strange behaviour on Disk Manipulators

### ISSUE THREAD

**Issue by DevPGSV** [starforcraft/Cable-Tiers#31]
Testing with a Ultra Disk Manipulator:

- Clicking on "Redstone Mode" works as expected
- Clicking on "IO Mode" to change from Insert to Extract does nothing (doesn't change the mode, displays no logs)
- Clicking on "Type" to change to Fluid does not work (it keeps on item Mode) and display logs on server:
<details>
<summary>Log</summary>
<pre>
[10:35:44] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: class com.YTrollman.CableTiers.node.TieredDiskManipulatorNetworkNode cannot be cast to class com.refinedmods.refinedstorage.blockentity.config.IPrioritizable (com.YTrollman.CableTiers.node.TieredDiskManipulatorNetworkNode is in module cabletiers@1.18.1-0.545 of loader 'TRANSFORMER' @3206174f; com.refinedmods.refinedstorage.blockentity.config.IPrioritizable is in module refinedstorage@1.10.0 of loader 'TRANSFORMER' @3206174f)
        at com.refinedmods.refinedstorage.blockentity.config.IPrioritizable.lambda$createParameter$1(IPrioritizable.java:10) ~[refinedstorage-1.10.0.jar%23112!/:1.10.0]
        at com.refinedmods.refinedstorage.network.sync.BlockEntitySynchronizationParamaterUpdateMessage.lambda$handle$0(BlockEntitySynchronizationParamaterUpdateMessage.java:53) ~[refinedstorage-1.10.0.jar%23112!/:1.10.0]
        at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:222) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at com.refinedmods.refinedstorage.network.sync.BlockEntitySynchronizationParamaterUpdateMessage.handle(BlockEntitySynchronizationParamaterUpdateMessage.java:46) ~[refinedstorage-1.10.0.jar%23112!/:1.10.0]
        at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:82) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:82) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:89) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:89) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1416) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
</pre>
</details>

- The "Mode" button is always set on Whitelist. If I click it to change it to blacklist, it doesn't change the mode... instead, it changes the first button  "Redstone mode" to the value "Only work with redstone signal"
- Clicking on "Exact mode" to enable/disable it doesn't work, and it displays logs on server:

<details>
<summary>Log</summary>
<pre>
[10:39:47] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: class com.YTrollman.CableTiers.node.TieredDiskManipulatorNetworkNode cannot be cast to class com.refinedmods.refinedstorage.blockentity.config.IAccessType (com.YTrollman.CableTiers.node.TieredDiskManipulatorNetworkNode is in module cabletiers@1.18.1-0.545 of loader 'TRANSFORMER' @3206174f; com.refinedmods.refinedstorage.blockentity.config.IAccessType is in module refinedstorage@1.10.0 of loader 'TRANSFORMER' @3206174f)
        at com.refinedmods.refinedstorage.blockentity.config.IAccessType.lambda$createParameter$1(IAccessType.java:11) ~[refinedstorage-1.10.0.jar%23112!/:1.10.0]
        at com.refinedmods.refinedstorage.network.sync.BlockEntitySynchronizationParamaterUpdateMessage.lambda$handle$0(BlockEntitySynchronizationParamaterUpdateMessage.java:53) ~[refinedstorage-1.10.0.jar%23112!/:1.10.0]
        at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:222) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at com.refinedmods.refinedstorage.network.sync.BlockEntitySynchronizationParamaterUpdateMessage.handle(BlockEntitySynchronizationParamaterUpdateMessage.java:46) ~[refinedstorage-1.10.0.jar%23112!/:1.10.0]
        at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:82) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:82) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:89) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:89) ~[forge-1.18.1-39.0.59-universal.jar%23142!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1416) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
</pre>
</details>

Tested with:
- [cabletiers-1.18.1-0.545.jar](https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3623371)
- [refinedstorage-1.10.0.jar](https://www.curseforge.com/minecraft/mc-mods/refined-storage/files/3623324)
- Minecraft: 1.18.1
- forge-1.18.1-39.0.59-installer.jar (from https://files.minecraftforge.net/net/minecraftforge/forge/ )

**Comment by starforcraft** [comment]
Server or Singleplayer?

**Comment by DevPGSV** [comment]
Multiplayer, server administrated by me.
I've just restarted the server, and now:

- Clicking on any of the 5 buttons does nothing
- Only the "Exact Mode" button displays a stack trace on the server when clicked. The other buttons display nothing.
