### ISSUE TITLE
Error preventing player from logging in

### ISSUE THREAD

**Issue by grimscar** [starforcraft/Cable-Tiers#49]
I was curious if this Error has anything you might be able to help us understand what's going on and maybe how we might fix it on our server? It appeared to be an issue with CableTiers and we're assuming it's the Creative Importer because that was the last action they took before being booted.  Placing one down in the world. but it wasn't the first one ever placed. Tons were used before this.

`<html>
<body>

[30Mar2023 09:30:59.709] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
--
1549 | java.lang.ClassCastException: class com.refinedmods.refinedstorage.apiimpl.network.node.ImporterNetworkNode cannot be cast to class com.YTrollman.CableTiers.node.TieredImporterNetworkNode (com.refinedmods.refinedstorage.apiimpl.network.node.ImporterNetworkNode is in module refinedstorage@1.11.5 of loader 'TRANSFORMER' @1c2096c6; com.YTrollman.CableTiers.node.TieredImporterNetworkNode is in module cabletiers@1.19.2-0.5471 of loader 'TRANSFORMER' @1c2096c6)
1550 | at com.YTrollman.CableTiers.blockentity.TieredImporterBlockEntity.writeUpdate(TieredImporterBlockEntity.java:49) ~[cabletiers-1.19.2-0.5471.jar%23484!/:1.19.2-0.5471]
1551 | at com.refinedmods.refinedstorage.blockentity.BaseBlockEntity.m_5995_(BaseBlockEntity.java:35) ~[refinedstorage-1.11.5.jar%23673!/:1.11.5]
1552 | at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:152) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1553 | at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1554 | at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1555 | at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1210) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1556 | at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1557 | at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:1009) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1558 | at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1131) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1559 | at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:459) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1560 | at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1576) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1561 | at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1559) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1562 | at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:136) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1563 | at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:97) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1564 | at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1565 | at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:796) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1566 | at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1567 | at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:198) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1568 | at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1569 | at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1570 | at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1571 | at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1572 | at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1573 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1574 | at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1575 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1576 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1577 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
1578 | at java.lang.Thread.run(Thread.java:833) [?:?]

</body>
</html>[30Mar2023 09:30:59.709] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
java.lang.ClassCastException: class com.refinedmods.refinedstorage.apiimpl.network.node.ImporterNetworkNode cannot be cast to class com.YTrollman.CableTiers.node.TieredImporterNetworkNode (com.refinedmods.refinedstorage.apiimpl.network.node.ImporterNetworkNode is in module refinedstorage@1.11.5 of loader 'TRANSFORMER' @1c2096c6; com.YTrollman.CableTiers.node.TieredImporterNetworkNode is in module cabletiers@1.19.2-0.5471 of loader 'TRANSFORMER' @1c2096c6)
	at com.YTrollman.CableTiers.blockentity.TieredImporterBlockEntity.writeUpdate(TieredImporterBlockEntity.java:49) ~[cabletiers-1.19.2-0.5471.jar%23484!/:1.19.2-0.5471]
	at com.refinedmods.refinedstorage.blockentity.BaseBlockEntity.m_5995_(BaseBlockEntity.java:35) ~[refinedstorage-1.11.5.jar%23673!/:1.11.5]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:152) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1210) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:1009) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1131) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:459) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1576) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:[1559](https://mclo.gs/qgJhA2b#L1559)) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_[1575](https://mclo.gs/qgJhA2b#L1575)75_(PersistentEntitySectionManager.java:136) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:97) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:796) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:198) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23763!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by starforcraft** [comment]
This is the cause: https://github.com/refinedmods/refinedstorage/issues/3449
