### ISSUE TITLE
crashed my server for person in chunk

### ISSUE THREAD

**Issue by killerkitt** [starforcraft/Cable-Tiers#59]
i am using all the mods 9,
to replicate it is hard to say cause it seems like there was just multiple in the same chunk
doesn't load the chunk if you are another player looking at the chunk but when you enter it crashes
this is the error that pops up when said person had the crash

java.lang.ClassCastException: class com.ultramega.cabletiers.node.TieredExporterNetworkNode cannot be cast to class com.refinedmods.refinedstorage.apiimpl.network.node.ExporterNetworkNode (com.ultramega.cabletiers.node.TieredExporterNetworkNode is in module cabletiers@1.20.1-1.1 of loader 'TRANSFORMER' @bea5941; com.refinedmods.refinedstorage.apiimpl.network.node.ExporterNetworkNode is in module refinedstorage@1.12.3 of loader 'TRANSFORMER' @bea5941)
	at com.refinedmods.refinedstorage.blockentity.ExporterBlockEntity.writeUpdate(ExporterBlockEntity.java:60) ~[refinedstorage-1.12.3.jar%23676!/:?]
	at com.refinedmods.refinedstorage.blockentity.BaseBlockEntity.m_5995_(BaseBlockEntity.java:35) ~[refinedstorage-1.12.3.jar%23676!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:152) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1261) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:892) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:1035) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1158) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:465) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1505) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1488) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:136) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:97) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:75) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:834) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:215) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23755!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by starforcraft** [comment]
Will be fixed as soon as RS v1.12.4 is out https://github.com/refinedmods/refinedstorage/issues/3424#issuecomment-1793718977
